sudo: required
services:
  - docker

before_install:
  - docker build -t martintds/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true martintds/docker-react/docker-react npm run test
